# Generated by Django 2.2.4 on 2019-08-25 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_from', models.CharField(default=None, max_length=50, null=True)),
                ('done', models.BooleanField(default=False)),
                ('question_01', models.IntegerField(default=0)),
                ('question_02', models.IntegerField(default=0)),
                ('question_03', models.IntegerField(default=0)),
                ('question_04', models.IntegerField(default=0)),
                ('question_05', models.IntegerField(default=0)),
                ('question_06', models.IntegerField(default=0)),
                ('question_07', models.IntegerField(default=0)),
                ('question_08', models.IntegerField(default=0)),
                ('question_09', models.IntegerField(default=0)),
                ('question_10', models.IntegerField(default=0)),
                ('question_11', models.IntegerField(default=0)),
                ('question_12', models.IntegerField(default=0)),
                ('question_13', models.IntegerField(default=0)),
                ('question_14', models.IntegerField(default=0)),
                ('question_15', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
